FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY etl/ ./etl/
COPY model/ ./model/
COPY api/ ./api/

EXPOSE 8000

CMD python etl/extract.py && \
    python model/train.py && \
    python model/train_supervisado.py && \
    uvicorn api.main:app --host 0.0.0.0 --port 8000