FROM python:3.11

WORKDIR /app

COPY dashboards/requirements.txt .
RUN pip install -r requirements.txt

COPY dashboards/ ./dashboards/

EXPOSE 8501

CMD ["streamlit", "run", "dashboards/app.py", "--server.address=0.0.0.0"]